<?php
echo "\n"; 
echo "\n"; 
echo "\n"; 
echo "<!DOCTYPE html>\n"; 
echo "<html>\n"; 
echo "<head>\n"; 
echo "<title>Venkat Reddy's Portfolio</title>\n"; 
echo "<link href=\"css/bootstrap.css\" rel=\"stylesheet\">\n"; 
echo "\n"; 
echo "\n"; 
echo "\n"; 
echo "\n"; 
echo "\n"; 
echo "\n"; 
echo "<link href=\"css/style.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\" />\n"; 
echo "<!-- for-mobile-apps -->\n"; 
echo "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"; 
echo "<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\n"; 
echo "<meta name=\"keywords\" content=\"Venkat Reddy has vast knowledge from his bachelor degree study period. He built web site for his own class and maintained for 60 students to share pics and results and everything\" />\n"; 
echo "<script type=\"application/x-javascript\"> addEventListener(\"load\", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>\n"; 
echo "<!-- //for-mobile-apps -->		\n"; 
echo "<!--fonts-->\n"; 
echo "<link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,700,300,600,800,400' rel='stylesheet' type='text/css'>\n"; 
echo "<link href='http://fonts.googleapis.com/css?family=Signika:700,300,400,600' rel='stylesheet' type='text/css'>\n"; 
echo "<!--//fonts-->\n"; 
echo "<script src=\"js/jquery.min.js\"> </script>\n"; 
echo "<!-- Bootstrap core JavaScript\n"; 
echo "================================================== -->\n"; 
echo "<!-- Placed at the end of the document so the pages load faster -->\n"; 
echo "<!-- js -->\n"; 
echo "<script src=\"js/bootstrap.js\"></script>\n"; 
echo "<!-- js -->\n"; 
echo "<script type=\"text/javascript\" src=\"js/move-top.js\"></script>\n"; 
echo "<script type=\"text/javascript\" src=\"js/easing.js\"></script>\n"; 
echo "<!--/script-->\n"; 
echo "<script type=\"text/javascript\">\n"; 
echo "jQuery(document).ready(function($) {\n"; 
echo "$(\".scroll\").click(function(event){		\n"; 
echo "event.preventDefault();\n"; 
echo "$('html,body').animate({scrollTop:$(this.hash).offset().top},900);\n"; 
echo "});\n"; 
echo "});\n"; 
echo "</script>\n"; 
echo "</head>\n"; 
echo "<body>\n"; 
echo "<!--header-->\n"; 
echo "<div id=\"home\" class=\"header\">\n"; 
echo "		<div class=\"header-top\">\n"; 
echo "			<div class=\"container\">\n"; 
echo "					<div class=\"header-right-text\">\n"; 
echo "						<h3>Contact Me:<span>(770)-336-6576     </span></h3>\n"; 
echo "						<h3><span>venkatreddy.y08@gmail.com</span></h3>\n"; 
echo "<h3><span>admin@venkatreddy.dx.am</span></h3>\n"; 
echo "					</div>\n"; 
echo "					<div class=\"header-btn\">\n"; 
echo "						\n"; 
echo "						\n"; 
echo "						\n"; 
echo "						\n"; 
echo "						\n"; 
echo "						\n"; 
echo "						<input type=\"text\" name=\"TextBox\" id=\"TextBox\" value=\"0\" />\n"; 
echo "						<input type=\"Button\" id='AddButton' value=\"Say Hello\" />\n"; 
echo "  					\n"; 
echo "				        <script>\n"; 
echo "				            $(document).ready(function(){\n"; 
echo "				                $('#AddButton').click( function() {\n"; 
echo "				                    var counter = $('#TextBox').val();\n"; 
echo "				                    counter++ ;\n"; 
echo "				                    action=\"sayhellos.php\"\n"; 
echo "				                    $('#TextBox').val(counter);\n"; 
echo "				                });\n"; 
echo "				            });\n"; 
echo "				        </script>\n"; 
echo "					\n"; 
echo "						\n"; 
echo "					</div>\n"; 
echo "			</div>\n"; 
echo "			<div class=\"clearfix\"> </div>\n"; 
echo "		</div>\n"; 
echo "<div class=\"header-nav effect2\">\n"; 
echo "	<div class=\"container\">\n"; 
echo "		<div class=\"navigation\">\n"; 
echo "			<nav class=\"navbar navbar-default\">\n"; 
echo "				<div class=\"navbar-header\">\n"; 
echo "					  <button type=\"button\" class=\"navbar-toggle collapsed\" data-toggle=\"collapse\" data-target=\"#bs-example-navbar-collapse-1\">\n"; 
echo "						<span class=\"sr-only\">Toggle navigation</span>\n"; 
echo "						<span class=\"icon-bar\"> </span>\n"; 
echo "						<span class=\"icon-bar\"> </span>\n"; 
echo "						<span class=\"icon-bar\"> </span>\n"; 
echo "					  </button>\n"; 
echo "					</div>\n"; 
echo "					<div class=\"collapse navbar-collapse nav-wil\" id=\"bs-example-navbar-collapse-1\">\n"; 
echo "					  <ul class=\"nav navbar-nav\">\n"; 
echo "						<li class=\"active\"><a href=\"home.php\">Home <span class=\"sr-only\">(current)</span></a></li>\n"; 
echo "						<li><a class=\"scroll\" href=\"#Connect\">Connect Me</a></li>\n"; 
echo "						<li><a class=\"scroll\" href=\"#Contact\">Contact Me</a></li>\n"; 
echo "					  </ul>\n"; 
echo "			  <div class=\"clearfix\"> </div>\n"; 
echo "			</div><!-- /.navbar-collapse -->\n"; 
echo "		</nav>\n"; 
echo "	</div>\n"; 
echo "	</div>\n"; 
echo "	</div>\n"; 
echo "	<div class=\"clearfix\"> </div>\n"; 
echo "</div>\n"; 
echo "			  <!-- script-for-menu -->\n"; 
echo "		 <script>\n"; 
echo "				$(\"span.menu\").click(function(){\n"; 
echo "					$(\".top-nav ul\").slideToggle(\"slow\" , function(){\n"; 
echo "					});\n"; 
echo "				});\n"; 
echo "		 </script>\n"; 
echo "		 <!-- script-for-menu -->\n"; 
echo "<div class=\"banner\">\n"; 
echo "	<div class=\"container\" >\n"; 
echo "		<div class=\"grid__item color-9\" align=\"center\">\n"; 
echo "				<a class=\"link link--ilin\" href=\"#\"><span>Ven</span><span>kat</span></a>\n"; 
echo "			</div>\n"; 
echo "		<p>   A &nbsp creative &nbsp iOS application & Web &nbsp developer </p>\n"; 
echo "	</div>\n"; 
echo "</div>\n"; 
echo "<div class=\"content-part\">\n"; 
echo "<div class=\"body-pic\">\n"; 
echo "	<div class=\"container\">\n"; 
echo "		<img src=\"images/body.png\" />\n"; 
echo "	</div>\n"; 
echo "	<div class=\"body-pic-bottom\">	\n"; 
echo "</div>\n"; 
echo "</div>\n"; 
echo "<br/>\n"; 
echo "<br/>\n"; 
echo "<br/>\n"; 
echo "<br/>\n"; 
echo "<br/>\n"; 
echo "<br/>\n"; 
echo "\n"; 
echo "<div id=\"Portfolio\" class=\"portfolio\" align=\"center\">\n"; 
echo "			\n"; 
echo "        \n"; 
echo "				\n"; 
echo "<img src=\"images\VenkatExperienceLettersoftcopy.jpg\" style=\"height:1200px; width:1000px;\" class=\"img-responsive\" alt=\"\"> \n"; 
echo "\n"; 
echo "</div>\n"; 
echo "\n"; 
echo "<div class=\"clearfix\"> </div>\n"; 
echo "<div id=\"Connect\" class=\"skills\">\n"; 
echo "<h3>Connect Me</h3>\n"; 
echo "<div class=\"social-icon\">\n"; 
echo "<div class=\"container\" align=\"center\">\n"; 
echo "<br/>\n"; 
echo "<br/>\n"; 
echo "<br/>\n"; 
echo "<a href=\"https://www.linkedin.com/in/venkat-reddy-954961112?trk=hp-identity-name\">\n"; 
echo "		<div class=\"linkdin\">\n"; 
echo "			<span class=\"icon4\"> </span>\n"; 
echo "			<label><i>About</i> <br />Me</label>\n"; 
echo "		</div>\n"; 
echo "		</a>		\n"; 
echo "<a href=\"https://twitter.com/VenkatYedavally\">\n"; 
echo "		<div class=\"twitter\">\n"; 
echo "			<span class=\"icon2\"> </span>\n"; 
echo "			<label><i>Follow</i> <br />Me</label>\n"; 
echo "		</div>\n"; 
echo "		</a>\n"; 
echo "<a href=\"https://www.youtube.com/channel/UCn_-vMGsbBKfcHhko8VFMmw\">\n"; 
echo "		<div class=\"youtube\">\n"; 
echo "			<span class=\"icon3\"> </span>\n"; 
echo "			<label><i>About</i> <br />Me</label>	\n"; 
echo "		</div>\n"; 
echo "		</a>\n"; 
echo "<a href=\"https://www.facebook.com/venkatyadavally1992\">\n"; 
echo "		<div class=\"facebook\">\n"; 
echo "			<span class=\"icon1\"> </span>\n"; 
echo "			<label><i>Follow</i> <br />Me</label>\n"; 
echo "		</div>\n"; 
echo "		</a>\n"; 
echo "		<div class=\"clearfix\"> </div>\n"; 
echo "</div>\n"; 
echo "	<div id=\"Contact\" class=\"contact\">\n"; 
echo "	<div class=\"container\">\n"; 
echo "		<div class=\"content_middle_bottom\">\n"; 
echo "          <h3 class=\"tz-title-3\">Get In Touch</h3>\n"; 
echo "		  <h4>I would love to hear from you! Get in touch with me.</h4>\n"; 
echo "		</div>\n"; 
echo "<div class=\"col-sm-4 map\">\n"; 
echo "<h3>Give Your Message!</h3>	\n"; 
echo "<br />\n"; 
echo "<p>I am located in Atlanta, GA, but am looking for positions all over the country. If you are interested in working with me, shoot me an email using the form on the right and I will get back to you. Thanks!</p>\n"; 
echo "<br/>\n"; 
echo "<p> Ph No: (770)-336-6576  \n"; 
echo "<br />\n"; 
echo "<br/>\n"; 
echo "<br />\n"; 
echo "		<iframe src=\"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d6605.413573802012!2d-84.24549480000006!3d34.128255499999995!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x88f57642f4395211%3A0x988af8d5b9ea6ae3!2sAlpharetta%2C+GA+30004!5e0!3m2!1sen!2sus!4v1443949729040\" width=\"500\" height=\"500\" frameborder=\"0\" style=\"border:0\" allowfullscreen></iframe>\n"; 
echo "</div>\n"; 
echo "<div class=\"col-sm-8 grid_2\">\n"; 
echo "<iframe src=\"https://docs.google.com/forms/d/1IIwhYt0V9MkySO67bgzR_I53zhIpHa8i-kCaj_PUdMc/viewform?embedded=true\" width=\"600\" height=\"762\" frameborder=\"0\" marginheight=\"0\" marginwidth=\"0\">Loading...</iframe>\n"; 
echo "</div>\n"; 
echo "<div class=\"clearfix\"> </div>\n"; 
echo "	</div>\n"; 
echo "</div>\n"; 
echo "<div class=\"footer\">\n"; 
echo "	<div class=\"copy\">\n"; 
echo "	<p>This site works perfect in Google Chrome. Support for other browsers will be updated soon.</p>\n"; 
echo "		<p>Copyrights © 2013 Venkat Reddy. All rights reserved </p>\n"; 
echo "</div>\n"; 
echo "\n"; 
echo "							\n"; 
echo "										<script type=\"text/javascript\">\n"; 
echo "										\n"; 
echo "										\n"; 
echo "\n"; 
echo "											\n"; 
echo "    \n"; 
echo "\n"; 
echo "\n"; 
echo "\n"; 
echo "										$(document).ready(function(){\n"; 
echo "\n"; 
echo "											$().UItoTop({ easingType: 'easeOutQuart' });\n"; 
echo "\n"; 
echo "											\n"; 
echo "\n"; 
echo "											$(\"#buttonHide\").click(function(){\n"; 
echo "                            				$(\"#hideContent\").hide();\n"; 
echo "                       						 });\n"; 
echo "											\n"; 
echo "										\n"; 
echo "											});\n"; 
echo "										\n"; 
echo "\n"; 
echo "										\n"; 
echo "										</script>\n"; 
echo "									\n"; 
echo "							\n"; 
echo "					\n"; 
echo "				<a href=\"#\" id=\"toTop\" style=\"display: block;\"><span id=\"toTopHover\"></span> <span id=\"toTopHover\" style=\"opacity: 1;\"> </span></a>\n"; 
echo "</div>\n"; 
echo "\n"; 
echo "</body>\n"; 
echo "</html>\n";
?>